### ISSUE TITLE
How to build?

### ISSUE THREAD

**Issue by e1001925** [CailyPersonal/WechatMultiOpenTool#1]
Hi, thanks for sharing. But how to build this? It seems application inside bin is not working.

**Comment by xunyard** [comment]
It's a Visual Studio solution including two projects. So open file 'WechatMultiOpenTool.sln' with Visual Studio 2012 or later, build it, and you will get two files named 'WeChatJailbreak.dll' and 'WechatMultiOpenTool.exe'. Put them in the same directory and run the application. CAUTION: WeChat must by installed on disk 'C:' or it won't work!
